
var tipuesearch = {"pages": [
	{"title":"Android Async Task","text":"Through this article we will look at one of the important feature of Android i.e AsyncTask for performing task which takes long time for execution with example. Also we will look at other mechanisms and see why AsyncTask is better approach.","tags":"Android Async Task","url":"/post/android/async_task"},
	{"title":"Change Preference Summary","text":"In Today's post we are going to look at How to Change Summary of Edit Text Preference.","tags":"Android Preferences","url":"/post/android/change_preference"},
	{"title":"Introduction to Android UI Layouts","text":"Considering the fact that available space on mobile screen is small, UI design of mobile application is very important. For Android each screen follows one or more layout.","tags":"Android Introduction","url":"/post/android/introduction"},
	{"title":"Android Menus","text":"Menus are one of the most important parts of any application and when it comes to mobile Menus become more important considering the fact that area available is restricted. Through this blog we will  look at the following various type of Android Menus available with example for each of them.","tags":"Android Menus","url":"/post/android/menus"},
	{"title":"Android Preferences","text":"Most of applications have some setting which user can/needs to configure, and to do this setting a screen needs to be designed along with code to read the data and display and update the data back.","tags":"Android Preferences","url":"/post/android/preferences"},
	{"title":"Introduction to Android SQLite Database","text":"Android provide various options for data persistence like Preferences, File and Database etc. This post we will introduce you to one of the option i.e. Android SQLite Database.","tags":"Android Database Sqlite","url":"/post/android/sqlite"},
	{"title":"Basics: Types, Variables and Constants","text":"In today's post we will learn basics of Go language like supported Types, how to declare and initialize variables and constants. Just like any other language, Go has its own way of declaring and initializing variables and constants.","tags":"Basics Constants Data Types Go GoLang Variables","url":"/post/golang/basics"},
	{"title":"Channels","text":"Go's concurrency model is based on Do not communicate by sharing memory; instead, share memory by communicating, and Channels is the way of achieving this.","tags":"Channels Concurrency Go GoLang","url":"/post/golang/channels"},
	{"title":"Control Flows","text":"The best part of programming in Go is that there are not multiple ways of doing standard things and that makes reading code and understanding it easier. But at the same time as we saw in previous post Go follows different conventions which needs to be understood.","tags":"Control Flows Go GoLang","url":"/post/golang/controlflows"},
	{"title":"Defer","text":"Going by literal meaning of the word Defer, means “put off an action or event to later time i.e. postponed”. And in case of GO to the usage of keyword is to defer/postponed the execution.","tags":"Defer Go GoLang","url":"/post/golang/defer"},
	{"title":"Functions and Pointers","text":"Go, does not have keywords like private, public, protected and final etc and Go does not have concept of inheritance so it is very important to understand how functions can be used to do things that we ideally do when we use any other language.","tags":"Function Pointers Go GoLang","url":"/post/golang/functions_pointers"},
	{"title":"Interface and Composition","text":"In today's post we are going to look at how Go supports interface and composition. Interface and composition form the base of any language and Go is no different.","tags":"Interface Composition Go GoLang","url":"/post/golang/interface"},
	{"title":"Introduction to GoLang","text":"GoLang is an open source language developed and backed by internet giant Google. GoLang is famously known as Go and that is how we are going to refer to in future. In 2007, Robert Griesemer, Rob Pike and Ken Thompson at Google started with experiment to develop a language that will have minimal of features","tags":"GoLang Go Introduction","url":"/post/golang/introduction"},
	{"title":"Struct, Map, Array and Slice","text":"Go is not a traditional OO language and hence does not have concept of class. Instead structures are used for holding values.","tags":"Go GoLang","url":"/post/golang/more_datatypes"},
	{"title":"Go Routine","text":"One of the most talked feature of Go is its support for Concurrency and Go Routine and Channel are the two most important instrument provided by Go for concurrency. In today's blog we will try and understand what Go Routine is and how to use it. But before start, let us try and understand what Concurrency is?","tags":"Routine Concurrency Go GoLang","url":"/post/golang/routines"}
]};